### PR TITLE
Only install change detectors if has document cookies

### PR DESCRIPTION
**Pull request by meros**
Closes: #419

### CODE REVIEW

**Comment by MINWONAHN** [comment]
How about changing the code as below to eliminate the fundamental cause of memory leaks?

AS-IS
```javascript
  private _startPolling() {
    this.pollingInterval = setInterval(this.update, 300);
  }

  private _stopPolling() {
    if (this.pollingInterval) {
      clearInterval(this.pollingInterval);
    }
  }
```

TO-BE
```javascript
  private _startPolling() {
    this._stopPolling();
    this.pollingInterval = setInterval(this.update, 300);
  }

  private _stopPolling() {
    if (this.pollingInterval) {
      clearInterval(this.pollingInterval);
    }
  }
```

**Comment by meros** [comment]
This is not the reason for the leak (references earlier comment). The leak springs from the interval keeping a reference to this, not letting that object expire. Combine this with other code that assumed that it is ok to not unregister Change listeners (including the express middleware) and you get leaks.

Now, this PR is not a perfect fix, but in any case we don't need the interval unless HAS_DOCUMENT_COOKIES is true. So this change is good in any case...

**Comment by MINWONAHN** [comment]
> The leak springs from the interval keeping a reference to this, not letting that object expire.


I believe that _startPolling must be cleared before setInterval(this.update, 300); because if you repeatedly call _startPolling without clearing it, setInterval can cause a memory leak.

```javascript
  private _startPolling() {
    this.pollingInterval = setInterval(this.update, 300);
  }
```

**Comment by meros** [comment]
> > The leak springs from the interval keeping a reference to this, not letting that object expire.
> 
> I believe that _startPolling must be cleared before setInterval(this.update, 300); because if you repeatedly call _startPolling without clearing it, setInterval can cause a memory leak.
> 
> ```js
>   private _startPolling() {
>     this.pollingInterval = setInterval(this.update, 300);
>   }
> ```

Yeah, well ok but that is not the reason for the leak. There is a guard when calling _startPolling/_stopPolling functions to avoid these being called multiple times. Again, the reason for the leak is that the interval that is running has a reference to this, which keeps the object alive even if no one else has a reference.

**Comment by eXon** [comment]
Merged in #431

**Pull request closed without merging**
